import streamlit as st
import pandas as pd
import numpy as np
from scipy.stats import poisson

# --- 1. PAGE CONFIGURATION ---
st.set_page_config(page_title="World Cup 2026 Simulator", page_icon="🏆", layout="wide")
st.title("🏆 FIFA World Cup 2026: AI & Monte Carlo Simulator")
st.markdown("""
Welcome to the ultimate predictive model for the 2026 World Cup. 
Powered by historical match data, dynamic FIFA rankings, Transfermarkt financial valuations, and a Bivariate Poisson distribution.
""")

# --- SIDEBAR & LEGAL DISCLAIMER ---
st.sidebar.title("About the Simulator")
st.sidebar.info(
    "Developed by **Lucas Rodriguez Saa** as a Data Science portfolio project."
)

st.sidebar.markdown("---")
st.sidebar.markdown("### ⚠️ Legal Disclaimer")
st.sidebar.markdown("""
This application is an educational and demonstration tool. 

The probabilities and predictions generated by this Monte Carlo model **do not constitute financial, gambling, or betting advice**. 

Sports are inherently unpredictable, and mathematical models based on historical data cannot guarantee future real-world outcomes. Please do not use this data for real-money betting.
""")

# --- 2. DATA LOADING (CACHED) ---
@st.cache_data
def load_data():
    # Carga de los 3 archivos que subiste a GitHub
    df_group_preds = pd.read_csv('WC26_GroupStage_Predictions.csv')
    df_str = pd.read_csv('WC26_Team_Strengths.csv').set_index('Team')
    df_timeline = pd.read_csv('WC26_Full_Tournament_Profiles.csv')
    return df_group_preds, df_str, df_timeline

df_group_preds, df_str, df_timeline = load_data()
teams_list = sorted(df_str.index.tolist())

# --- 3. TABS CREATION ---
tab1, tab2, tab3 = st.tabs(["📊 The Oracle (10k Simulations)", "⚔️ Match Predictor", "🌌 Multiverse Explorer"])

# === TAB 1: GROUP STAGE PREDICTIONS ===
with tab1:
    st.header("Group Stage: Official Fixture Predictions")
    st.markdown("Probabilities for all 72 group stage matches based on our SPI-adjusted model.")
    
    # Formateo visual para la tabla
    st.dataframe(
        df_group_preds.style.format({
            "Prob_Win_A_%": "{:.1f}%", 
            "Prob_Draw_%": "{:.1f}%", 
            "Prob_Win_B_%": "{:.1f}%", 
            "Score_Probability_%": "{:.1f}%"
        }), 
        use_container_width=True, 
        height=600,
        hide_index=True
    )

# === TAB 2: LIVE MATCH PREDICTOR ===
with tab2:
    st.header("Live Match Predictor")
    st.markdown("Select any two qualified teams. The engine will calculate their Expected Goals (xG) and generate the probability matrix using a Dixon-Coles adjusted Poisson distribution.")
    
    col1, col2 = st.columns(2)
    with col1:
        team_a = st.selectbox("Select Team A:", teams_list, index=teams_list.index("Argentina") if "Argentina" in teams_list else 0)
    with col2:
        team_b = st.selectbox("Select Team B:", teams_list, index=teams_list.index("France") if "France" in teams_list else 1)
    
    if st.button("Predict Match", type="primary"):
        if team_a == team_b:
            st.error("Please select two different teams.")
        else:
            # --- POISSON MATH ENGINE (Cálculo en vivo) ---
            american_teams = ['Argentina', 'Brazil', 'Uruguay', 'Colombia', 'Ecuador', 'Paraguay', 'Mexico', 'United States', 'Canada', 'Panama', 'Haiti', 'Curaçao']
            
            # Stochastic Noise & Continental Advantage
            luck_a = np.random.uniform(1.0, 1.10) if team_a in american_teams else 1.0
            luck_b = np.random.uniform(1.0, 1.10) if team_b in american_teams else 1.0
            
            avg_gs = 1.45
            lambda_a = avg_gs * (df_str.loc[team_a, 'Adjusted_Attack'] * luck_a) * df_str.loc[team_b, 'Adjusted_Defense']
            lambda_b = avg_gs * (df_str.loc[team_b, 'Adjusted_Attack'] * luck_b) * df_str.loc[team_a, 'Adjusted_Defense']
            
            max_goals = 7
            goals = np.arange(max_goals + 1)
            prob_matrix = np.outer(poisson.pmf(goals, lambda_a), poisson.pmf(goals, lambda_b))
            
            # Dixon-Coles Adjustment
            rho = -0.05
            prob_matrix[0, 0] *= (1 - lambda_a * lambda_b * rho)
            prob_matrix[0, 1] *= (1 + lambda_a * rho)
            prob_matrix[1, 0] *= (1 + lambda_b * rho)
            prob_matrix[1, 1] *= (1 - rho)
            prob_matrix = np.maximum(0, prob_matrix)
            prob_matrix /= prob_matrix.sum()

            # Format Results Matrix
            results = []
            for i in range(max_goals + 1):
                for j in range(max_goals + 1):
                    results.append({'Scoreline': f"{team_a} {i} - {j} {team_b}", 'Probability_%': prob_matrix[i, j] * 100})
            
            df_res = pd.DataFrame(results).sort_values('Probability_%', ascending=False).reset_index(drop=True)
            
            # Metrics
            prob_win_a = np.tril(prob_matrix, -1).sum() * 100
            prob_draw = np.trace(prob_matrix) * 100
            prob_win_b = np.triu(prob_matrix, 1).sum() * 100
            
            st.markdown("### Match Odds")
            metric_col1, metric_col2, metric_col3 = st.columns(3)
            metric_col1.metric(f"{team_a} Win", f"{prob_win_a:.1f}%")
            metric_col2.metric("Draw", f"{prob_draw:.1f}%")
            metric_col3.metric(f"{team_b} Win", f"{prob_win_b:.1f}%")
            
            st.markdown("---")
            
            # --- TOP 5 & BOTTOM 5 PRESENTATION ---
            col_res1, col_res2 = st.columns(2)
            with col_res1:
                st.success("🎯 Top 5 Most Likely Scorelines")
                st.dataframe(
                    df_res.head(5).style.format({'Probability_%': "{:.2f}%"}), 
                    use_container_width=True, 
                    hide_index=True
                )
                
            with col_res2:
                st.warning("🚨 Top 5 Most Unlikely Scorelines (Glitches in the Matrix)")
                # Filtrar probabilidades matemáticas absurdas (menores a 0.05%) para mantener realismo
                df_unlikely = df_res[df_res['Probability_%'] >= 0.05]
                st.dataframe(
                    df_unlikely.tail(5).sort_values('Probability_%', ascending=True).style.format({'Probability_%': "{:.2f}%"}), 
                    use_container_width=True, 
                    hide_index=True
                )

# === TAB 3: TIMELINE EXPLORER ===
with tab3:
    st.header("Multiverse Explorer: The Master Timeline")
    st.markdown("Explore the 103 match simulations from **Seed 1986** (The exact timeline where Argentina wins the World Cup).")
    
    # Selector interactivo para filtrar por fase
    stages = ["All Matches"] + list(df_timeline['Stage'].unique())
    selected_stage = st.selectbox("Filter by Tournament Stage:", stages)
    
    if selected_stage != "All Matches":
        df_display = df_timeline[df_timeline['Stage'] == selected_stage]
    else:
        df_display = df_timeline
        
    st.dataframe(
        df_display.style.format({
            "Logical_Prob_%": "{:.2f}%", 
            "Unexpected_Prob_%": "{:.2f}%"
        }), 
        use_container_width=True, 
        hide_index=True
    )

